version: '3.8'

services:
  app:
    build: .
    container_name: construccionesguerrero
    restart: unless-stopped
    ports:
      - "127.0.0.1:3013:80"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
